<template>
	<div class="scan-results">
		<h2>
			{{ t('integration_gptzero', 'Document overall results') }}
		</h2>
		<div class="overall-results">
			<p>
				{{ t('integration_gptzero', 'Average generated probability:') }}
				{{ average_generated_prob }}
				<NcProgressBar :value="document.average_generated_prob" :size="'small'" :max="100" />
			</p>
			<p style="font-size: 0.85em">
				{{ t('integration_gptzero', 'The average of the probabilties that each sentence was generated by an AI') }}
			</p>
			<p>
				{{ t('integration_gptzero', 'Completely generated probability:') }}
				{{ completely_generated_prob }}
				({{ completelyGeneratedProbText() }})
				<NcProgressBar :value="document.completely_generated_prob" :size="'small'" :max="100" />
			</p>
			<p style="font-size: 0.85em">
				{{ t('integration_gptzero', 'The probability that the entire document was generated by an AI') }}
			</p>
			<p>
				{{ t('integration_gptzero', 'Overall burstiness:') }}
				{{ overall_burstiness }}
				<NcProgressBar :value="document.overall_burstiness" :size="'small'" :max="100" />
			</p>
			<p style="font-size: 0.85em">
				{{ t('integration_gptzero', 'The amount of variation in the perplexity of the document. A useful indicator to distinguish AI and human written text') }}
			</p>
		</div>
		<h2 class="document-paragraphs" @click="showParagraphs = !showParagraphs">
			{{ t('integration_gptzero', 'Paragraphs') }}
			<Triangle :size="16" :class="{'triangle-icon-rotate': showParagraphs}" />
		</h2>
		<div v-if="showParagraphs" class="paragraphs">
			<ParagraphMark v-for="paragraph in paragraphs"
				:key="paragraph.id"
				:paragraph="paragraph"
				:sentences="sentences" />
		</div>
		<h2 class="document-sentences" @click="showSentences = !showSentences">
			{{ t('integration_gptzero', 'Sentences') }}
			<Triangle :size="16" :class="{'triangle-icon-rotate': showSentences}" />
		</h2>
		<div v-if="showSentences" class="sentences">
			<SentenceMark v-for="sentence in sentences"
				:key="sentence.id"
				:sentence="sentence" />
		</div>
	</div>
</template>

<script>
import { loadState } from '@nextcloud/initial-state'

import NcProgressBar from '@nextcloud/vue/dist/Components/NcProgressBar.js'

import ParagraphMark from './ParagraphMark.vue'
import SentenceMark from './SentenceMark.vue'
import Triangle from 'vue-material-design-icons/Triangle.vue'

export default {
	name: 'ScanResults',
	components: {
		NcProgressBar,
		ParagraphMark,
		SentenceMark,
		Triangle,
	},
	props: {
		document: {
			type: Object,
			required: true,
		},
		selectedFiles: {
			type: Array,
			required: true,
			default: () => [],
		},
	},
	data() {
		return {
			showParagraphs: false,
			showSentences: this.selectedFiles.length <= 1,
			completely_generated_prob_config: loadState('integration_gptzero', 'completely_generated_prob_config', { min: 0.22, max: 0.5 }),
		}
	},
	computed: {
		average_generated_prob() {
			return this.document.average_generated_prob
		},
		completely_generated_prob() {
			return this.document.completely_generated_prob
		},
		overall_burstiness() {
			return this.document.overall_burstiness
		},
		paragraphs() {
			return this.document.paragraphs
		},
		sentences() {
			return this.document.sentences
		},
	},
	methods: {
		completelyGeneratedProbText() {
			if (this.document.completely_generated_prob < this.completely_generated_prob_config.min) {
				return t('integration_gptzero', 'Most likely written by a Human')
			} else if (this.document.completely_generated_prob > this.completely_generated_prob_config.max) {
				return t('integration_gptzero', 'Most likely generated by an AI')
			} else if (this.document.completely_generated_prob >= this.completely_generated_prob_config.min && this.document.completely_generated_prob <= this.completely_generated_prob_config.max) {
				return t('integration_gptzero', 'Partially based on input or other sources. Unknown really')
			}
		},
	},
}
</script>

<style lang="scss" scoped>
.scan-results {
	width: 100%;
	padding: 10px;
	margin: 20px auto;
	border: 1px solid var(--color-border-dark);
	border-radius: var(--border-radius);

	& .overall-results {
		margin-bottom: 1rem;
	}

	.triangle-icon-rotate {
		transform: rotate(180deg);
	}

	.document-paragraphs, .document-sentences {
		display: flex;
		align-items: center;
		cursor: pointer;
		user-select: none;

		.material-design-icon {
			margin-left: 10px;
		}
	}
}
</style>
