<template>
	<div class="scan-results">
		<div class="overall-results">
			<p>
				{{ t('integration_gptzero', 'Average generated probability:') }}
				{{ average_generated_prob }}
				<NcProgressBar :value="average_generated_prob" :size="'small'" :max="1000" />
			</p>
			<p style="font-size: 0.85em">
				{{ t('integration_gptzero', 'The average of the probabilties that each sentence was generated by an AI') }}
			</p>
			<p>
				{{ t('integration_gptzero', 'Completely generated probability:') }}
				{{ completely_generated_prob }}
				<NcProgressBar :value="completely_generated_prob" :size="'small'" :max="1000" />
			</p>
			<p style="font-size: 0.85em">
				{{ t('integration_gptzero', 'The probability that the entire document was generated by an AI') }}
			</p>
			<p>
				{{ t('integration_gptzero', 'Overall burstiness:') }}
				{{ overall_burstiness }}
				<NcProgressBar :value="overall_burstiness" :size="'small'" :max="1000" />
			</p>
			<p style="font-size: 0.85em">
				{{ t('integration_gptzero', 'The amount of variation in the perplexity of the document. A useful indicator to distinguish AI and human written text') }}
			</p>
		</div>
		<div v-if="false" class="paragraphs">
			<ParagraphMark v-for="paragraph in paragraphs"
				:key="paragraph.id"
				:paragraph="paragraph" />
		</div>
		<div class="sentences">
			<h2>
				{{ t('integration_gptzero', 'Sentences') }}
			</h2>
			<SentenceMark v-for="sentence in sentences"
				:key="sentence.id"
				:sentence="sentence" />
		</div>
	</div>
</template>

<script>
import NcProgressBar from '@nextcloud/vue/dist/Components/NcProgressBar.js'

import ParagraphMark from './ParagraphMark.vue'
import SentenceMark from './SentenceMark.vue'

export default {
	name: 'ScanResults',
	components: {
		NcProgressBar,
		ParagraphMark,
		SentenceMark,
	},
	props: {
		document: {
			type: Object,
			required: true,
		},
	},
	data() {
		return {
		}
	},
	computed: {
		average_generated_prob() {
			return this.document.average_generated_prob.toFixed(3)
		},
		completely_generated_prob() {
			return this.document.completely_generated_prob.toFixed(3)
		},
		overall_burstiness() {
			return this.document.overall_burstiness.toFixed(3)
		},
		paragraphs() {
			return this.document.paragraphs
		},
		sentences() {
			return this.document.sentences
		},
	},
	methods: {
	},
}
</script>

<style lang="scss" scoped>
.scan-results {
	width: 100%;

	& .overall-results {
		margin-bottom: 1rem;
	}
}
</style>
