<template>
	<div class="sentence-mark">
		<div class="sentence-mark__text"
			:class="{'sentence-mark__text_generated': sentence.generated_prob === 1}"
			:v-tooltip="{content: generatedProbabilityText, placement: 'top'}">
			{{ sentence.sentence }}
		</div>
		<div class="sentence-mark__generated_prob">
			{{ generatedProbabilityText }}
			{{ perplexityText }}
		</div>
	</div>
</template>

<script>
export default {
	name: 'SentenceMark',
	props: {
		sentence: {
			type: Object,
			required: true,
		},
	},
	data() {
		return {
		}
	},
	computed: {
		generatedProbabilityText() {
			if (this.sentence.generated_prob === 1) {
				return t('integration_gptzero', 'This sentence is likely to be generated by the AI model')
			}
			return t('integration_gptzero', 'Most likely written by a Human')
		},
		perplexityText() {
			return t('integration_gptzero', 'Perplexity: {perplexity} (the lower - the more likely generated by an AI)', { perplexity: this.sentence.perplexity })
		},
	},
	methods: {
	},
}
</script>

<style lang="scss" scoped>
.sentence-mark {
	margin-bottom: 10px;

	&__text {
		font-size: 1.1em;

		&_generated {
			background-color: #ffff00;
			padding: 5px 10px;
			border-radius: var(--border-radius);
		}

		body[data-theme-dark] &_generated {
			color: #000;
		}
	}

	&__generated_prob {
		font-size: 0.85em;
		color: #5b5600;
	}

	body[data-theme-dark] & {
		&__generated_prob {
			color: #c8c264;
		}
	}
}
</style>
