<template>
	<div class="sentence-mark">
		<div class="sentence-mark__text"
			:class="{'sentence-mark__text_generated': sentence.generated_prob === 1}"
			:v-tooltip="{content: generatedPropabilityText, placement: 'top'}">
			{{ sentence.sentence }}
		</div>
		<div class="sentense-mark_generated_prob">
			{{ generatedPropabilityText }}
			{{ perplexityText }}
		</div>
	</div>
</template>

<script>
export default {
	name: 'SentenceMark',
	props: {
		sentence: {
			type: Object,
			required: true,
		},
	},
	data() {
		return {
		}
	},
	computed: {
		generatedPropabilityText() {
			if (this.sentence.generated_prob === 1) {
				return t('integration_gptzero', 'This sentence is likely to be generated by the AI model.')
			}
			return t('integration_gptzero', 'This sentence is not generated by the AI model.')
		},
		perplexityText() {
			return t('integration_gptzero', 'Perplexity: {perplexity}', { perplexity: this.sentence.perplexity })
		},
	},
	methods: {
	},
}
</script>

<style lang="scss" scoped>
.sentence-mark {
	margin-bottom: 10px;

	&__text {
		font-size: 1.2em;

		&_generated {
			font-weight: bold;
			background-color: var(--color-error-hover);
			padding: 5px 10px;
			border-radius: var(--border-radius);
		}
	}

	&__generated_prob {
		font-size: 0.8em;
	}
}
</style>
