<template>
	<NcContent app-name="integration_gptzero">
		<GPTZeroNav :predict-results-history.sync="predictResultsHistory"
			:text="text"
			:selected-files="selectedFiles"
			@load-history-item="loadHistoryItem"
			@delete-history-item="deleteHistoryItem"
			@save-history-to-local-storage="saveHistoryToLocalStorage"
			@clear-history="clearHistory" />
		<NcAppContent>
			<div class="gptzero-app">
				<div class="gptzero-app-heading">
					<h2>
						<GPTZeroIcon class="gptzero-icon" />
						{{ t('integration_gptzero', 'GPTZero integration') }}
					</h2>
					<p class="description">
						{{ t('integration_gptzero', 'This app allows you to check if the text you are writing is likely to be generated by the AI model.') }}
					</p>
					<p class="pre-caution">
						<InformationOutlineIcon :size="20" class="icon" style="margin-right: 5px;" />
						{{ t('integration_gptzero', 'All the text you are typing or files you select will be sent to the GPTZero API service. Please do not use any sensitive data.') }}
					</p>
				</div>
				<textarea v-if="selectedFiles.length === 0"
					v-model="text"
					cols="80"
					rows="5"
					:placeholder="t('integration_gptzero', 'Type in the text in which you want to detect AI implication (minimum 250 characters)')" />
				<FilesSelection v-else
					:files="selectedFiles"
					@remove-file-selection="removeFile" />
				<div class="terms-of-service">
					<NcCheckboxRadioSwitch :checked.sync="acceptGPTZeroTermsOfService"
						style="margin-right: 10px;">
						{{ t('integration_gptzero', 'I agree to the terms of service') }}
					</NcCheckboxRadioSwitch>
					<NcButton href="https://gptzero.me/terms-of-use.html" target="_blank" type="tertiary">
						<template #icon>
							<OpenInNew :size="18" />
						</template>
					</NcButton>
				</div>
				<div class="actions">
					<NcButton :disabled="predicting"
						type="primary"
						@click="getResults">
						<template #icon>
							<span v-if="predicting" class="material-icon icon-loading-small" />
							<GPTZeroIcon v-else :size="18" />
						</template>
						{{ t('integration_gptzero', 'Get results') }}
					</NcButton>
					<NcButton type="secondary"
						style="margin: 0 10px;"
						@click="selectFiles">
						<template #icon>
							<FileMultiple :size="20" />
						</template>
						{{ selectFilesButtonText }}
					</NcButton>
					<NcButton @click="clearInputs">
						<template #icon>
							<span class="material-icon icon-close" />
						</template>
						{{ t('integration_gptzero', 'Clear') }}
					</NcButton>
				</div>
			</div>
			<div v-if="predictResult" class="documents">
				<div v-for="document, index in predictResult" :key="index">
					<ScanResults
						:document="document"
						:document-index="Number(index)"
						:selected-files="selectedFiles" />
				</div>
			</div>
		</NcAppContent>
	</NcContent>
</template>

<script>
import axios from '@nextcloud/axios'
import { generateUrl } from '@nextcloud/router'
import { getFilePickerBuilder, showError, showSuccess } from '@nextcloud/dialogs'

import NcContent from '@nextcloud/vue/dist/Components/NcContent.js'
import NcAppContent from '@nextcloud/vue/dist/Components/NcAppContent.js'
import NcButton from '@nextcloud/vue/dist/Components/NcButton.js'
import NcCheckboxRadioSwitch from '@nextcloud/vue/dist/Components/NcCheckboxRadioSwitch.js'

import InformationOutlineIcon from 'vue-material-design-icons/InformationOutline.vue'
import FileMultiple from 'vue-material-design-icons/FileMultiple.vue'
import OpenInNew from 'vue-material-design-icons/OpenInNew.vue'
import GPTZeroIcon from './components/icons/GPTZeroIcon.vue'

import GPTZeroNav from './components/GPTZeroNav.vue'
import ScanResults from './components/ScanResults.vue'
import FilesSelection from './components/FilesSelection.vue'

import { requestFileInfo, parseFileInfoToObject } from './utils/files.js'

export default {
	name: 'App',
	components: {
		NcContent,
		NcAppContent,
		NcButton,
		NcCheckboxRadioSwitch,
		InformationOutlineIcon,
		FileMultiple,
		OpenInNew,
		GPTZeroIcon,
		GPTZeroNav,
		ScanResults,
		FilesSelection,
	},
	data() {
		return {
			text: '',
			predictResult: {},
			predicting: false,
			predictResultsHistory: [],
			selectedFiles: [],
			acceptGPTZeroTermsOfService: false,
		}
	},
	computed: {
		predictResultText() {
			return JSON.stringify(this.predictResult, null, 2)
		},
		selectFilesButtonText() {
			if (this.selectedFiles.length === 0) {
				return t('integration_gptzero', 'Select files')
			} else {
				return t('integration_gptzero', 'Add files')
			}
		},
	},
	watch: {
		acceptGPTZeroTermsOfService() {
			this.saveTermsOfServiceAccept()
		},
	},
	beforeMount() {
		this.loadHistory()
		this.loadFileScanFromPath()
		this.loadTermsOfServiceAccept()
	},
	methods: {
		getResults() {
			if (!this.acceptGPTZeroTermsOfService) {
				showError(t('integration_gptzero', 'Please accept the terms of service to continue'))
				return
			}
			if (this.selectedFiles.length > 0) {
				this.postPredictFiles()
			} else {
				this.postPredictText()
			}
		},
		postPredictText() {
			if (this.text !== '' && this.text.length >= 250) {
				this.predicting = true
				this.predictResult = {}
				axios.post(generateUrl('/apps/integration_gptzero/predict/text'), {
					text: this.text.trim().replace(/(?:\r\n|\r|\n)/g, '\n'),
				}).then(res => {
					this.predictResult = res.data
					this.predicting = false
					this.addToHistory({
						textHash: this.getTextHash(this.text),
						text: this.text,
						predictResult: this.predictResult,
					})
				}).catch(err => {
					console.error(err)
					this.predicting = false
					showError(t('integration_gptzero', 'Error while scanning text'))
				})
			} else {
				showError(t('integration_gptzero', 'Please enter at least 250 characters or select files to scan'))
			}
		},
		postPredictFiles() {
			if (this.selectedFiles.length > 0) {
				this.predicting = true
				this.predictResult = {}
				axios.post(generateUrl('/apps/integration_gptzero/predict/files'), {
					fileIds: this.selectedFiles.map(f => f.fileid),
				}).then(res => {
					if (res.data.error) {
						showError(res.data.error)
						this.predicting = false
						return
					}
					this.predictResult = res.data
					this.addToHistory({
						fileIds: this.selectedFiles.map(f => f.fileid).join(','),
						selectedFiles: [...this.selectedFiles],
						predictResult: { ...this.predictResult },
					})
					this.predicting = false
				}).catch(err => {
					console.error(err)
					this.predicting = false
					showError(t('integration_gptzero', 'Error while scanning files'))
				})
			} else {
				showError(t('integration_gptzero', 'Please select at least one file'))
			}
		},
		selectFiles() {
			this.getFilesPicker(t('integration_notion', 'Select files for scan')).pick()
				.then((files) => {
					files.forEach((file) => {
						requestFileInfo(file)
							.then((fileInfo) => {
								if (this.selectedFiles.findIndex(f => f.path === file) === -1) {
									this.selectedFiles.push({
										path: file, ...parseFileInfoToObject(fileInfo.data),
									})
									this.text = ''
									this.predictResult = {}
								}
							})
					})
				})
		},
		removeFile(file) {
			this.selectedFiles = this.selectedFiles.filter(f => f.fileid !== file.fileid)
		},
		getFilesPicker(title) {
			return getFilePickerBuilder(title)
				.setMultiSelect(true)
				.setModal(true)
				.setMimeTypeFilter(['text/plain', 'application/pdf', 'application/msword'])
				.setType(1)
				.allowDirectories(false)
				.build()
		},
		loadFileScanFromPath() {
			let filePath = window.location.href.split('?filePath=')[1]
			if (filePath) {
				filePath = decodeURIComponent(filePath)
				requestFileInfo(filePath)
					.then((fileInfo) => {
						this.selectedFiles.push({
							path: filePath, ...parseFileInfoToObject(fileInfo.data),
						})
					})
			}
		},
		loadTermsOfServiceAccept() {
			const accept = localStorage.getItem('gptzero-accept-terms-of-service')
			if (accept) {
				this.acceptGPTZeroTermsOfService = JSON.parse(accept)
			}
		},
		saveTermsOfServiceAccept() {
			localStorage.setItem('gptzero-accept-terms-of-service', JSON.stringify(this.acceptGPTZeroTermsOfService))
		},
		loadHistory() {
			const history = localStorage.getItem('gptzero-predict-results-history')
			if (history) {
				this.predictResultsHistory = JSON.parse(history)
			}
		},
		loadHistoryItem(historyPredictResult) {
			if ('text' in historyPredictResult) {
				this.text = historyPredictResult.text
				this.predictResult = historyPredictResult.predictResult
				this.selectedFiles = []
			}
			if ('selectedFiles' in historyPredictResult) {
				this.text = ''
				this.selectedFiles = [...historyPredictResult.selectedFiles]
				this.predictResult = { ...historyPredictResult.predictResult }
			}
		},
		deleteHistoryItem(historyItem) {
			if ('text' in historyItem) {
				this.predictResultsHistory = this.predictResultsHistory.filter(item => item.textHash !== historyItem.textHash)
				this.saveHistoryToLocalStorage()
			}
			if ('selectedFiles' in historyItem) {
				this.predictResultsHistory = this.predictResultsHistory.filter(item => item.fileIds !== historyItem.fileIds)
				this.saveHistoryToLocalStorage()
			}
		},
		saveHistoryToLocalStorage() {
			localStorage.setItem('gptzero-predict-results-history', JSON.stringify(this.predictResultsHistory))
			showSuccess(t('integration_gptzero', 'History saved.'))
		},
		clearHistory() {
			this.predictResultsHistory = []
			this.saveHistoryToLocalStorage()
		},
		addToHistory(item) {
			if ('text' in item) {
				if (this.predictResultsHistory.filter(historyItem => historyItem.textHash === item.textHash).length === 0) {
					if (this.predictResultsHistory.length >= 7) {
						this.predictResultsHistory.shift()
					}
					this.predictResultsHistory.push(item)
					this.saveHistoryToLocalStorage()
				} else {
					const historyItemIndex = this.predictResultsHistory.findIndex(historyItem => historyItem.textHash === item.textHash)
					this.predictResultsHistory.splice(historyItemIndex, 1)
					this.predictResultsHistory.push(item)
					this.saveHistoryToLocalStorage()
				}
			}
			if ('selectedFiles' in item) {
				if (this.predictResultsHistory.filter(historyItem => 'selectedFiles' in historyItem).filter(historyItem => historyItem.fileIds === item.fileIds).length === 0) {
					if (this.predictResultsHistory.length >= 7) {
						this.predictResultsHistory.shift()
					}
					this.predictResultsHistory.push(item)
					this.saveHistoryToLocalStorage()
				} else {
					const historyItemIndex = this.predictResultsHistory.findIndex(historyItem => 'selectedFiles' in historyItem && historyItem.fileIds === item.fileIds)
					this.predictResultsHistory.splice(historyItemIndex, 1)
					this.predictResultsHistory.push(item)
					this.saveHistoryToLocalStorage()
				}
			}
		},
		getTextHash(text) {
			let hash = 0
			let i, chr
			if (text.length === 0) return hash
			for (i = 0; i < text.length; i++) {
				chr = text.charCodeAt(i)
				hash = ((hash << 5) - hash) + chr
				hash |= 0
			}
			return hash
		},
		clearInputs() {
			this.text = ''
			this.predictResult = {}
			this.selectedFiles = []
		},
	},
}
</script>

<style lang="scss" scoped>
.gptzero-app {
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: center;
	margin: 0 auto;
	width: 100%;
	overflow-y: auto;
	padding: 20px;

	textarea {
		width: auto;
	}

	.terms-of-service {
		display: flex;
		align-items: center;
		margin: 10px auto;
	}

	.actions {
		margin: 10px 0;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	@media (max-width: 568px) {
		textarea {
			width: 100%;
		}
		.actions {
			width: 100%;
			flex-direction: column;

			button {
				margin: 5px 0 !important;
			}
		}

		.documents {
			width: 85%;
		}
	}

	h2 {
		display: flex;
		justify-content: center;

		.gptzero-icon {
			margin-right: 10px;
		}
	}

	&-heading {
		margin: 0 0 20px;

		.description {
			text-align: center;
		}

		.pre-caution {
			display: flex;
			align-items: center;
			color: var(--color-text-maxcontrast-default);
		}
	}
}

.documents {
	width: 75%;
	margin: 20px auto;
	// border: 1px solid var(--color-border-dark);
	// border-radius: var(--border-radius);
	// padding: 10px;

	h2 {
		text-align: center;
	}
}
</style>
