<template>
	<NcContent app-name="integration_gptzero">
		<GPTZeroNav :predict-results-history.sync="predictResultsHistory"
			@load-history-item="loadHistoryItem"
			@delete-history-item="deleteHistoryItem"
			@save-history-to-local-storage="saveHistoryToLocalStorage"
			@clear-history="clearHistory" />
		<NcAppContent>
			<div class="gptzero-app">
				<div class="gptzero-app-heading">
					<h2>
						<GPTZeroIcon class="gptzero-icon" />
						{{ t('integration_gptzero', 'GPTZero integration') }}
					</h2>
					<p class="description">
						{{ t('integration_gptzero', 'This app allows you to check if the text you are writing is likely to be generated by the AI model.') }}
					</p>
					<p class="pre-caution">
						<InformationOutlineIcon :size="20" class="icon" style="margin-right: 5px;" />
						{{ t('integration_gptzero', 'All the text you are typing is sent to the GPTZero API service. Please do not use any sensitive data.') }}
					</p>
				</div>
				<textarea v-if="selectedFiles.length === 0"
					v-model="text"
					cols="80"
					rows="5"
					:placeholder="t('integration_gptzero', 'Type in the text in which you want to detect AI implication (minimum 250 characters)')" />
				<FilesSelection v-else
					:files="selectedFiles"
					@remove-file-selection="removeFile" />
				<div class="actions">
					<NcButton :disabled="predicting"
						type="primary"
						@click="getResults">
						<template #icon>
							<span v-if="predicting" class="material-icon icon-loading-small" />
							<GPTZeroIcon v-else :size="18" />
						</template>
						{{ t('integration_gptzero', 'Get results') }}
					</NcButton>
					<NcButton type="secondary"
						style="margin: 0 10px;"
						@click="selectFiles">
						<template #icon>
							<FileMultiple :size="20" />
						</template>
						{{ t('integration_gptzero', 'Select files') }}
					</NcButton>
					<NcButton v-if="selectedFiles.length === 0"
						style="margin: 0 10px;"
						@click="fillWithTestText">
						{{ t('integration_gptzero', 'Fill with test text') }}
					</NcButton>
					<NcButton v-if="selectedFiles.length === 0"
						style="margin: 0 10px;"
						@click="fillTestResults">
						{{ t('integration_gptzero', 'Fill test results') }}
					</NcButton>
					<NcButton @click="clearInputs">
						{{ t('integration_gptzero', 'Clear') }}
					</NcButton>
				</div>
				<!-- <textarea v-if="predictResultText !== '{}'"
					cols="80"
					rows="5"
					:value="predictResultText" /> -->
			</div>
			<div v-if="'documents' in predictResult" class="documents">
				<h2>
					{{ t('integration_gptzero', 'Results') }}
				</h2>
				<div v-for="document in predictResult.documents"
					:key="document.overall_burstiness">
					<ScanResults :document="document" />
				</div>
			</div>
		</NcAppContent>
	</NcContent>
</template>

<script>
import axios from '@nextcloud/axios'
import { generateUrl } from '@nextcloud/router'
import { getFilePickerBuilder, showError, showSuccess } from '@nextcloud/dialogs'

import NcContent from '@nextcloud/vue/dist/Components/NcContent.js'
import NcAppContent from '@nextcloud/vue/dist/Components/NcAppContent.js'
import NcButton from '@nextcloud/vue/dist/Components/NcButton.js'

import InformationOutlineIcon from 'vue-material-design-icons/InformationOutline.vue'
import FileMultiple from 'vue-material-design-icons/FileMultiple.vue'
import GPTZeroIcon from './components/icons/GPTZeroIcon.vue'

import GPTZeroNav from './components/GPTZeroNav.vue'
import ScanResults from './components/ScanResults.vue'
import FilesSelection from './components/FilesSelection.vue'

import { requestFileInfo, parseFileInfoToObject } from './utils/files.js'

export default {
	name: 'App',
	components: {
		NcContent,
		NcAppContent,
		NcButton,
		InformationOutlineIcon,
		FileMultiple,
		GPTZeroIcon,
		GPTZeroNav,
		ScanResults,
		FilesSelection,
	},
	data() {
		return {
			text: '',
			predictResult: {},
			predicting: false,
			predictResultsHistory: [],
			selectedFiles: [],
			error: '',
		}
	},
	computed: {
		predictResultText() {
			return JSON.stringify(this.predictResult, null, 2)
		},
	},
	beforeMount() {
		this.loadHistory()
		this.loadFileScanFromPath()
	},
	methods: {
		getResults() {
			if (this.selectedFiles.length > 0) {
				this.postPredictFiles()
			} else {
				this.postPredictText()
			}
		},
		postPredictText() {
			if (this.text !== '' && this.text.length >= 250) {
				this.predicting = true
				this.predictResult = {}
				axios.post(generateUrl('/apps/integration_gptzero/predict/text'), {
					text: this.text.trim().replace(/(?:\r\n|\r|\n)/g, '\n'),
				}).then(res => {
					console.debug(res)
					this.predictResult = res.data
					this.predicting = false
					this.addToHistory({
						text: this.text,
						predictResult: this.predictResult,
					})
				}).catch(err => {
					console.error(err)
					this.predicting = false
					showError(t('integration_gptzero', 'Error while scanning text'))
					if ('error' in err.data) {
						this.error = err.data.error
					}
				})
			} else {
				showError(t('integration_gptzero', 'Please enter at least 250 characters'))
			}
		},
		postPredictFiles() {
			if (this.selectedFiles.length > 0) {
				this.predicting = true
				this.predictResult = {}
				axios.post(generateUrl('/apps/integration_gptzero/predict/files'), {
					fileIds: this.selectedFiles.map(f => f.fileid),
				}).then(res => {
					console.debug(res)
					this.predictResult = res.data
					this.predicting = false
				}).catch(err => {
					console.error(err)
					this.predicting = false
					showError(t('integration_gptzero', 'Error while scanning files'))
					if ('error' in err.data) {
						this.error = err.data.error
					}
				})
			} else {
				showError(t('integration_gptzero', 'Please select at least one file'))
			}
		},
		selectFiles() {
			this.getFilesPicker(t('integration_notion', 'Select files for scan')).pick()
				.then((files) => {
					console.debug(files)
					files.forEach((file) => {
						console.debug(file)
						requestFileInfo(file)
							.then((fileInfo) => {
								console.debug(parseFileInfoToObject(fileInfo.data))
								if (this.selectedFiles.findIndex(f => f.path === file) === -1) {
									this.selectedFiles.push({
										path: file, ...parseFileInfoToObject(fileInfo.data),
									})
								}
							})
					})
				})
		},
		removeFile(file) {
			this.selectedFiles = this.selectedFiles.filter(f => f.id !== file.id)
		},
		getFilesPicker(title) {
			return getFilePickerBuilder(title)
				.setMultiSelect(true)
				.setModal(true)
				.setType(1)
				.allowDirectories(false)
				.build()
		},
		loadFileScanFromPath() {
			// TODO: Request file info from fileid in path
			let filePath = window.location.href.split('?filePath=')[1]
			if (filePath) {
				filePath = decodeURIComponent(filePath)
				requestFileInfo(filePath)
					.then((fileInfo) => {
						console.debug(parseFileInfoToObject(fileInfo.data))
						this.selectedFiles.push({
							path: filePath, ...parseFileInfoToObject(fileInfo.data),
						})
					})
			}
		},
		loadHistory() {
			const history = localStorage.getItem('gptzero-predict-results-history')
			if (history) {
				this.predictResultsHistory = JSON.parse(history)
			}
		},
		loadHistoryItem(historyPredictResult) {
			this.text = historyPredictResult.text
			this.predictResult = historyPredictResult.predictResult
		},
		deleteHistoryItem(historyItem) {
			this.predictResultsHistory = this.predictResultsHistory.filter(item => item.text !== historyItem.text)
			this.saveHistoryToLocalStorage()
		},
		saveHistoryToLocalStorage() {
			localStorage.setItem('gptzero-predict-results-history', JSON.stringify(this.predictResultsHistory))
			showSuccess(t('integration_gptzero', 'History saved.'))
		},
		clearHistory() {
			this.predictResultsHistory = []
			this.saveHistoryToLocalStorage()
		},
		addToHistory(item) {
			if (this.predictResultsHistory.filter(historyItem => historyItem.text === item.text).length === 0) {
				if (this.predictResultsHistory.length >= 7) {
					this.predictResultsHistory.pop()
				}
				this.predictResultsHistory.push(item)
				this.saveHistoryToLocalStorage()
			}
		},
		fillWithTestText() {
			this.text = `Climate change refers to the long-term shift in global weather patterns caused by human activity, particularly the emission of greenhouse gases into the atmosphere.
The most significant greenhouse gas is carbon dioxide, which is primarily produced by burning fossil fuels such as coal, oil, and gas.
The consequences of climate change are already visible in the form of rising temperatures, melting glaciers and ice caps, and more frequent extreme weather events such as hurricanes, droughts, and floods.
Scientists said many of the species relied on snow cover remaining high on hills until late spring and even summer to ensure a moist environment.
They also said plants that thrived on lower ground in warmer conditions were spreading to mountain habitats.
Species found to be in decline include snow pearlwort, alpine lady-fern and alpine speedwell.
These changes have significant impacts on ecosystems, biodiversity, and human health, including increased risk of respiratory diseases, food and water shortages, and the spread of infectious diseases.
To address climate change, it is essential to reduce greenhouse gas emissions through a range of measures, including increased use of renewable energy sources, greater energy efficiency, and improved transportation systems.
Many countries have committed to reducing their carbon footprint through initiatives such as the Paris Agreement, which aims to limit global warming to below 2°C above pre-industrial levels.
`
		},
		fillTestResults() {
			// eslint-disable-next-line
			this.predictResult = {"documents":[{"average_generated_prob":0.6666666666666666,"completely_generated_prob":0.24473019769941715,"overall_burstiness":60.12232971191406,"paragraphs":[{"completely_generated_prob":0.8181818181818181,"num_sentences":1,"start_sentence_index":0},{"completely_generated_prob":0.8181818181818181,"num_sentences":1,"start_sentence_index":1},{"completely_generated_prob":0.8181818181818181,"num_sentences":1,"start_sentence_index":2},{"completely_generated_prob":0.11111111111111108,"num_sentences":1,"start_sentence_index":3},{"completely_generated_prob":0.11111111111111108,"num_sentences":1,"start_sentence_index":4},{"completely_generated_prob":0.11111111111111108,"num_sentences":1,"start_sentence_index":5},{"completely_generated_prob":0.8181818181818181,"num_sentences":1,"start_sentence_index":6},{"completely_generated_prob":0.8181818181818181,"num_sentences":1,"start_sentence_index":7},{"completely_generated_prob":0.8181818181818181,"num_sentences":1,"start_sentence_index":8}],"sentences":[{"generated_prob":1,"perplexity":9,"sentence":"Climate change refers to the long-term shift in global weather patterns caused by human activity, particularly the emission of greenhouse gases into the atmosphere."},{"generated_prob":1,"perplexity":6,"sentence":"The most significant greenhouse gas is carbon dioxide, which is primarily produced by burning fossil fuels such as coal, oil, and gas."},{"generated_prob":1,"perplexity":7,"sentence":"The consequences of climate change are already visible in the form of rising temperatures, melting glaciers and ice caps, and more frequent extreme weather events such as hurricanes, droughts, and floods."},{"generated_prob":0,"perplexity":71,"sentence":"Scientists said many of the species relied on snow cover remaining high on hills until late spring and even summer to ensure a moist environment."},{"generated_prob":0,"perplexity":112,"sentence":"They also said plants that thrived on lower ground in warmer conditions were spreading to mountain habitats."},{"generated_prob":0,"perplexity":169,"sentence":"Species found to be in decline include snow pearlwort, alpine lady-fern and alpine speedwell."},{"generated_prob":1,"perplexity":10,"sentence":"These changes have significant impacts on ecosystems, biodiversity, and human health, including increased risk of respiratory diseases, food and water shortages, and the spread of infectious diseases."},{"generated_prob":1,"perplexity":9,"sentence":"To address climate change, it is essential to reduce greenhouse gas emissions through a range of measures, including increased use of renewable energy sources, greater energy efficiency, and improved transportation systems."},{"generated_prob":1,"perplexity":5,"sentence":"Many countries have committed to reducing their carbon footprint through initiatives such as the Paris Agreement, which aims to limit global warming to below 2°C above pre-industrial levels."}]}]}
		},
		clearInputs() {
			this.text = ''
			this.predictResult = {}
			this.selectedFiles = []
		},
	},
}
</script>

<style lang="scss" scoped>
.gptzero-app {
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: center;
	margin: 0 auto;
	width: 100%;
	overflow-y: auto;
	padding: 20px;

	textarea {
		width: auto;
	}

	.actions {
		margin: 10px 0;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	h2 {
		display: flex;
		justify-content: center;

		.gptzero-icon {
			margin-right: 10px;
		}
	}

	&-heading {
		margin: 0 0 20px;

		.pre-caution {
			display: flex;
			align-items: center;
			color: var(--color-text-maxcontrast-default);
		}
	}
}

.documents {
	width: 70%;
	// height: 100%;
	// overflow: auto;
	margin: 20px auto;
	border: 1px solid var(--color-border-dark);
	border-radius: var(--border-radius);
	padding: 10px;

	h2 {
		text-align: center;
	}
}
</style>
