<template>
	<NcContent app-name="integration_gptzero">
		<NcAppNavigation>
			<NcAppNavigationCaption
				:title="t('integration_gptzero', 'GPTZero History')">
				<template #actions>
					<NcActionButton @click="saveHistoryToLocalStorage">
						<template #icon>
							<ContentSaveAll :size="20" />
						</template>
						{{ t('integration_gtpzero', 'Save history') }}
					</NcActionButton>
					<NcActionButton @click="clearHistory">
						<template #icon>
							<NotificationClearAll :size="20" />
						</template>
						{{ t('integration_gtpzero', 'Clear history') }}
					</NcActionButton>
				</template>
			</NcAppNavigationCaption>
			<template v-if="predictResultsHistory.length > 0">
				<NcAppNavigationItem v-for="historyItem in predictResultsHistory"
					:key="historyItem.text"
					:title="historyItem.text.substring(0, 50)"
					@click="loadHistoryItem(historyItem)">
					<template #actions>
						<NcActionButton @click="deleteHistoryItem(historyItem)">
							<template #icon>
								<span class="material-icon icon-delete" />
							</template>
							{{ t('integration_gtpzero', 'Delete') }}
						</NcActionButton>
					</template>
				</NcAppNavigationItem>
			</template>
			<NcEmptyContent v-else
				:title="t('integration_gprzero', 'History is empty')">
				<template #icon>
					<FormatListBulleted />
				</template>
			</NcEmptyContent>
		</NcAppNavigation>
		<NcAppContent>
			<div class="gptzero-app">
				<div class="gptzero-app-heading">
					<h2>
						<GPTZeroIcon class="gptzero-icon" />
						{{ t('integration_gptzero', 'GPTZero integration') }}
					</h2>
					<p class="description">
						{{ t('integration_gptzero', 'This app allows you to check if the text you are writing is likely to be generated by the AI model.') }}
					</p>
					<p class="pre-caution">
						<!-- Short pre-caution about that all the text is sent to GPTZero API service -->
						<InformationOutlineIcon :size="20" class="icon" style="margin-right: 5px;" />
						{{ t('integration_gptzero', 'All the text you are typing is sent to the GPTZero API service. Please do not use any sensitive data.') }}
					</p>
				</div>
				<textarea v-model="text"
					cols="80"
					rows="5"
					:placeholder="t('integration_gptzero', 'Type in the text in which you want to detect AI implication (minimum 250 characters)')" />
				<div class="actions">
					<NcButton :disabled="predicting"
						type="primary"
						@click="postPredictText">
						<template #icon>
							<span v-if="predicting" class="material-icon icon-loading-small" />
						</template>
						{{ t('integration_gptzero', 'Predict') }}
					</NcButton>
					<NcButton style="margin: 0 10px;" @click="fillWithTestText">
						{{ t('integration_gptzero', 'Fill with test text') }}
					</NcButton>
					<NcButton style="margin: 0 10px;" @click="fillTestResults">
						{{ t('integration_gptzero', 'Fill test results') }}
					</NcButton>
					<NcButton @click="clearInputs">
						{{ t('integration_gptzero', 'Clear') }}
					</NcButton>
				</div>
				<textarea v-if="predictResultText !== '{}'"
					cols="80"
					rows="5"
					:value="predictResultText" />
			</div>
			<div v-if="'documents' in predictResult" class="documents">
				<h2>
					{{ t('integration_gptzero', 'Results') }}
				</h2>
				<div v-for="document in predictResult.documents"
					:key="document.overall_burstiness">
					<div class="document">
						<div v-for="sentence in document.sentences"
							:key="sentence">
							<SentenceMark :sentence="sentence" />
						</div>
					</div>
				</div>
			</div>
		</NcAppContent>
	</NcContent>
</template>

<script>
import axios from '@nextcloud/axios'
import { generateUrl } from '@nextcloud/router'
import { showSuccess, showError } from '@nextcloud/dialogs'

import NcAppNavigation from '@nextcloud/vue/dist/Components/NcAppNavigation.js'
import NcAppNavigationCaption from '@nextcloud/vue/dist/Components/NcAppNavigationCaption.js'
import NcAppNavigationItem from '@nextcloud/vue/dist/Components/NcAppNavigationItem.js'
import NcEmptyContent from '@nextcloud/vue/dist/Components/NcEmptyContent.js'
import NcActionButton from '@nextcloud/vue/dist/Components/NcActionButton.js'
import NcContent from '@nextcloud/vue/dist/Components/NcContent.js'
import NcAppContent from '@nextcloud/vue/dist/Components/NcAppContent.js'
import NcButton from '@nextcloud/vue/dist/Components/NcButton.js'

import ContentSaveAll from 'vue-material-design-icons/ContentSaveAll.vue'
import FormatListBulleted from 'vue-material-design-icons/FormatListBulleted.vue'
import NotificationClearAll from 'vue-material-design-icons/NotificationClearAll.vue'
import InformationOutlineIcon from 'vue-material-design-icons/InformationOutline.vue'
import GPTZeroIcon from './components/icons/GPTZeroIcon.vue'

import SentenceMark from './components/SentenceMark.vue'

export default {
	name: 'App',
	components: {
		NcContent,
		NcAppContent,
		NcAppNavigation,
		NcAppNavigationCaption,
		FormatListBulleted,
		NcActionButton,
		NcButton,
		NcAppNavigationItem,
		NcEmptyContent,
		ContentSaveAll,
		NotificationClearAll,
		InformationOutlineIcon,
		GPTZeroIcon,
		SentenceMark,
	},
	data() {
		return {
			text: '',
			predictResult: {},
			predicting: false,
			predictResultsHistory: [],
		}
	},
	computed: {
		predictResultText() {
			return JSON.stringify(this.predictResult, null, 2)
		},
	},
	beforeMount() {
		this.fillWithTestText()
		this.fillTestResults()
		this.loadHistory()
	},
	methods: {
		postPredictText() {
			if (this.text !== '' && this.text.length >= 250) {
				this.predicting = true
				this.predictResult = {}
				axios.post(generateUrl('/apps/integration_gptzero/predict/text'), {
					text: this.text.trim().replace(/(?:\r\n|\r|\n)/g, '\n'),
				}).then(res => {
					console.debug(res)
					this.predictResult = res.data
					this.predicting = false
					this.addToHistory({
						text: this.text,
						predictResult: this.predictResult,
					})
				})
			} else {
				showError(t('integration_gptzero', 'Please enter at least 250 characters.'))
			}
		},
		loadHistory() {
			const history = localStorage.getItem('gptzero-predict-results-history')
			if (history) {
				this.predictResultsHistory = JSON.parse(history)
			}
		},
		loadHistoryItem(historyPredictResult) {
			this.text = historyPredictResult.text
			this.predictResult = historyPredictResult.predictResult
		},
		addToHistory(item) {
			if (this.predictResultsHistory.filter(historyItem => historyItem.text === item.text).length === 0) {
				this.predictResultsHistory.push(item)
				this.saveHistoryToLocalStorage()
			}
		},
		deleteHistoryItem(historyItem) {
			this.predictResultsHistory = this.predictResultsHistory.filter(item => item.text !== historyItem.text)
			this.saveHistoryToLocalStorage()
		},
		saveHistoryToLocalStorage() {
			localStorage.setItem('gptzero-predict-results-history', JSON.stringify(this.predictResultsHistory))
			showSuccess(t('integration_gptzero', 'History saved.'))
		},
		clearHistory() {
			this.predictResultsHistory = []
			this.saveHistoryToLocalStorage()
		},
		fillWithTestText() {
			this.text = `Climate change refers to the long-term shift in global weather patterns caused by human activity, particularly the emission of greenhouse gases into the atmosphere.
The most significant greenhouse gas is carbon dioxide, which is primarily produced by burning fossil fuels such as coal, oil, and gas.
The consequences of climate change are already visible in the form of rising temperatures, melting glaciers and ice caps, and more frequent extreme weather events such as hurricanes, droughts, and floods.
Scientists said many of the species relied on snow cover remaining high on hills until late spring and even summer to ensure a moist environment.
They also said plants that thrived on lower ground in warmer conditions were spreading to mountain habitats.
Species found to be in decline include snow pearlwort, alpine lady-fern and alpine speedwell.
These changes have significant impacts on ecosystems, biodiversity, and human health, including increased risk of respiratory diseases, food and water shortages, and the spread of infectious diseases.
To address climate change, it is essential to reduce greenhouse gas emissions through a range of measures, including increased use of renewable energy sources, greater energy efficiency, and improved transportation systems.
Many countries have committed to reducing their carbon footprint through initiatives such as the Paris Agreement, which aims to limit global warming to below 2°C above pre-industrial levels.
`
		},
		fillTestResults() {
			// eslint-disable-next-line
			this.predictResult = {"documents":[{"average_generated_prob":0.6666666666666666,"completely_generated_prob":0.24473019769941715,"overall_burstiness":60.12232971191406,"paragraphs":[{"completely_generated_prob":0.8181818181818181,"num_sentences":1,"start_sentence_index":0},{"completely_generated_prob":0.8181818181818181,"num_sentences":1,"start_sentence_index":1},{"completely_generated_prob":0.8181818181818181,"num_sentences":1,"start_sentence_index":2},{"completely_generated_prob":0.11111111111111108,"num_sentences":1,"start_sentence_index":3},{"completely_generated_prob":0.11111111111111108,"num_sentences":1,"start_sentence_index":4},{"completely_generated_prob":0.11111111111111108,"num_sentences":1,"start_sentence_index":5},{"completely_generated_prob":0.8181818181818181,"num_sentences":1,"start_sentence_index":6},{"completely_generated_prob":0.8181818181818181,"num_sentences":1,"start_sentence_index":7},{"completely_generated_prob":0.8181818181818181,"num_sentences":1,"start_sentence_index":8}],"sentences":[{"generated_prob":1,"perplexity":9,"sentence":"Climate change refers to the long-term shift in global weather patterns caused by human activity, particularly the emission of greenhouse gases into the atmosphere."},{"generated_prob":1,"perplexity":6,"sentence":"The most significant greenhouse gas is carbon dioxide, which is primarily produced by burning fossil fuels such as coal, oil, and gas."},{"generated_prob":1,"perplexity":7,"sentence":"The consequences of climate change are already visible in the form of rising temperatures, melting glaciers and ice caps, and more frequent extreme weather events such as hurricanes, droughts, and floods."},{"generated_prob":0,"perplexity":71,"sentence":"Scientists said many of the species relied on snow cover remaining high on hills until late spring and even summer to ensure a moist environment."},{"generated_prob":0,"perplexity":112,"sentence":"They also said plants that thrived on lower ground in warmer conditions were spreading to mountain habitats."},{"generated_prob":0,"perplexity":169,"sentence":"Species found to be in decline include snow pearlwort, alpine lady-fern and alpine speedwell."},{"generated_prob":1,"perplexity":10,"sentence":"These changes have significant impacts on ecosystems, biodiversity, and human health, including increased risk of respiratory diseases, food and water shortages, and the spread of infectious diseases."},{"generated_prob":1,"perplexity":9,"sentence":"To address climate change, it is essential to reduce greenhouse gas emissions through a range of measures, including increased use of renewable energy sources, greater energy efficiency, and improved transportation systems."},{"generated_prob":1,"perplexity":5,"sentence":"Many countries have committed to reducing their carbon footprint through initiatives such as the Paris Agreement, which aims to limit global warming to below 2°C above pre-industrial levels."}]}]}
		},
		clearInputs() {
			this.text = ''
			this.predictResult = {}
		},
	},
}
</script>

<style lang="scss" scoped>
.gptzero-app {
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: center;
	margin: 0 auto;
	width: 100%;
	overflow-y: auto;
	padding: 20px;

	textarea {
		width: auto;
	}

	.actions {
		margin: 10px 0;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	h2 {
		display: flex;
		justify-content: center;

		.gptzero-icon {
			margin-right: 10px;
		}
	}

	&-heading {
		margin: 0 0 20px;

		.pre-caution {
			display: flex;
			align-items: center;
			color: var(--color-text-maxcontrast-default);
		}
	}
}

.documents {
	width: 70%;
	// height: 100%;
	// overflow: auto;
	margin: 20px auto;
	border: 1px solid var(--border-color-dark);
	border-radius: var(--border-radius);

	h2 {
		text-align: center;
	}
}
</style>
